name: Blastique
favicon: null
layout_spectrum: 0.4275224185548723
typography_spectrum: 0.358108232030645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5391256562434137
  lightness: 0.4958576085045934
  saturation: 0.31677814736030996
  rhythmicContrast: 0.5438898175489157
purpose: []
